#!/usr/bin/env bash
# pipeline/stages/30-agent.sh Ã¢â‚¬â€ install the netbox-agent runtime + first-boot
# provisioning into the rootfs. The agent itself is plain JS under
# netbox-agent/ (built repo-side); this stage only stages the files and the
# systemd units that run them. The decrypt unit below carries the user's
# explicitly-requested inline comment about the auto-unlock keyfile tradeoff.
set -euo pipefail
TARGET=$1

# --- runtime placement ------------------------------------------------------
# Source tree is GENERATED by build.js from repo-root netbox-agent/ (see the
# header there). cp -a (not -r) so exec bits/modes survive staging; . (not *)
# so dotfiles are included and an empty/glob-miss source errors instead of
# silently staging nothing.
mkdir -p "$TARGET/opt/netbox-agent"
cp -a /work/pipeline/rootfs_files/opt/netbox-agent/. "$TARGET/opt/netbox-agent/"

# Presence gate — build-time, not boot-time. The rootfs MUST contain the full
# agent incl. the Step 1 security-signal modules; a tree that stages without
# them produced an appliance that monitors nothing while reporting healthy.
for f in agent.js provision.js \
         lib/graph.js lib/post_event.js lib/signal_emit.js lib/backup_risk.js \
         lib/enroll.js lib/issue_cert.js lib/tpm.js \
         lib/http_json.js lib/net_checks.js lib/fhir_r4.js lib/mirth_admin.js lib/ehr_check.js; do
  [ -f "$TARGET/opt/netbox-agent/$f" ] || {
    echo "30-agent: MISSING $f in staged rootfs (agent source not generated by build.js?)" >&2
    exit 1
  }
done

# --- systemd: LUKS auto-unlock via unencrypted /boot keyfile -----------------
cat > "$TARGET/etc/systemd/system/decrypt-data.service" <<'EOF'
[Unit]
Description=Unlock netbox LUKS data partition using /boot auto-unlock keyfile
DefaultDependencies=no
After=systemd-modules-load.service systemd-udev-settle.service
Before=local-fs-pre.target shutdown.target
Conflicts=shutdown.target

[Service]
Type=oneshot
# by-label links need udev settled; without it the first-boot race makes
# decrypt-data exit before /dev/disk/by-label/DATA exists (serial probe verified).
StandardOutput=journal+console
StandardError=journal+console
ExecStartPre=/usr/bin/udevadm settle --timeout=30
ExecStartPre=/bin/sh -c 'echo "DECRYPT_PRE"; ls -la /dev/disk/by-label/ || true; echo "DECRYPT_POST_LABELS"'
# Ã¢â€â‚¬Ã¢â€â‚¬ THREAT-MODEL BOUNDARY (Phase 3 input, decision 2) Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬
# The keyfile below lives on the small UNencrypted /boot partition. That is a
# deliberate tradeoff, not an oversight:
#   Ã¢â‚¬Â¢ PROTECTS: the threat model from spec Section 2 Ã¢â‚¬â€ a removed/stolen SSD
#     read on another machine. Without this keyfile the drive is ciphertext.
#   Ã¢â‚¬Â¢ DOES NOT PROTECT: an attacker with the WHOLE running appliance, who can
#     boot it (or mount both partitions) and read /boot/netbox.key to unlock
#     the data partition. TPM sealing would resist that; a keyfile cannot.
# The keyfile is generated at first boot and never leaves the device. Not
# network-bound (no Clevis/Tang) so a WAN outage can't block local boot Ã¢â‚¬â€
# downtime-mode availability beats key-sealing strength here.
# If this unit is ever "hardened" by moving the keyfile elsewhere or adding a
# network unlock server, re-read this comment before merging. 
# Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬
ExecStart=/bin/sh -c '\
  echo "decrypt: checking for existing keyfile"; \
  if [ ! -f /boot/netbox.key ]; then \
    echo "decrypt: no keyfile; generating"; \
    mkdir -p /boot; \
    mount -o rw /dev/sda2 /boot || { echo "decrypt: MOUNT FAILED"; exit 1; }; \
    mount | grep boot; \
    dd if=/dev/urandom of=/boot/netbox.key bs=512 count=1 status=none; \
    chmod 0400 /boot/netbox.key; \
    ls -la /boot/netbox.key; \
    cryptsetup luksFormat --batch-mode /dev/sda5 /boot/netbox.key || { echo "decrypt: LUKSFORMAT FAILED"; exit 1; }; \
    echo "decrypt: keyfile created and LUKS formatted"; \
  else \
    echo "decrypt: keyfile exists"; \
  fi; \
  echo "decrypt: opening LUKS"; \
  # Keep /boot mounted — cryptsetup needs the keyfile path at open time.
  # BOOT stays rw-mounted; the keyfile is 0600 root-only.
  cryptsetup open --key-file /boot/netbox.key /dev/sda5 netbox-data && echo "decrypt: opened"; \
  # First boot only: a freshly luksFormat-ed container has NO filesystem, so
  # mount would fail. mkfs exactly once, gated on blkid finding none — never
  # reformat a populated data partition.
  if ! blkid /dev/mapper/netbox-data >/dev/null 2>&1; then \
    echo "decrypt: no filesystem on data partition; mkfs.ext4"; \
    mkfs.ext4 -q /dev/mapper/netbox-data || { echo "decrypt: MKFS FAILED"; exit 1; }; \
    udevadm settle --timeout=30; \
    echo "decrypt: filesystem created"; \
  fi; \
  mkdir -p /data; mount /dev/mapper/netbox-data /data && echo "decrypt: /data mounted"'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
# Key file mode + LuksFormat(andFormat) above must match the agent's keyless
# path expectations exactly; do not soften to passphrase fallback.

# --- systemd: first-boot provisioning -------------------------------------
cat > "$TARGET/etc/systemd/system/netbox-firstboot.service" <<'EOF'
[Unit]
Description=Netbox first-boot provisioning (enroll into quarantine)
After=decrypt-data.service network-online.target
Requires=decrypt-data.service
Wants=network-online.target
ConditionPathExists=!/data/enrolled

[Service]
Type=oneshot
StandardOutput=journal+console
StandardError=journal+console
ExecStart=/usr/local/bin/node /opt/netbox-agent/provision.js
# Enrollment is one-shot; the renewal loop runs as the agent's daemon unit.

[Install]
WantedBy=multi-user.target
EOF

# --- systemd: ongoing agent (renewal loop + heartbeats) --------------------
cat > "$TARGET/etc/systemd/system/netbox-agent.service" <<'EOF'
[Unit]
Description=Netbox device agent (renewal loop + monitoring orchestrator)
After=netbox-firstboot.service
ConditionPathExists=/data/enrolled

[Service]
Type=simple
ExecStart=/usr/local/bin/node /opt/netbox-agent/agent.js
Restart=always
# journal+console: the acceptance harness and any field debugging read the
# agent's heartbeat/renewal lines off the serial console; without this the
# daemon's output is invisible outside the journal (both sibling units match).
StandardOutput=journal+console
StandardError=journal+console
# Renewal cadence ~50-55% of TTL lives in the agent, not here Ã¢â‚¬â€ a sysadmin
# editing the unit must not be able to widen the expiry silence window.

[Install]
WantedBy=multi-user.target
EOF

# --- binaries the rootfs needs but debootstrap leaves out -----------------
chroot "$TARGET" apt-get update
chroot "$TARGET" apt-get install -y --no-install-recommends \
  systemd-sysv nodejs cryptsetup ca-certificates \
  linux-image-amd64 grub-efi-amd64-bin tpm2-tools openssl
# Triggered once: previous builds installed _some_ bundles but never
# /usr/sbin/init, and an unsquashfs probe showed the missing binary. Make
# this an explicit gate so sub-package resolution can't silently slip in.
if ! chroot "$TARGET" test -f /usr/sbin/init; then
  echo "systemd-sysv install did not produce /usr/sbin/init" >&2
  exit 1
fi
cat > "$TARGET/usr/local/bin/node" <<'EOF'
#!/bin/sh
exec /usr/bin/node "$@"
EOF
chmod +x "$TARGET/usr/local/bin/node"

# systemd-networkd must be explicitly enabled — the wired DHCP config in
# 10-configure.sh is inert without it, and an appliance that boots with no IP
# can never enroll (provision.js saw ENETUNREACH/0.0.0.0 before this was on).
systemd-nspawn --directory="$TARGET" --quiet /bin/systemctl enable \
  systemd-networkd decrypt-data.service netbox-firstboot.service netbox-agent.service \
  2>/dev/null || \
chroot "$TARGET" /bin/sh -c \
  'systemctl enable systemd-networkd decrypt-data.service netbox-firstboot.service netbox-agent.service'

