#!/usr/bin/env bash
# pipeline/stages/30-agent.sh Ã¢â‚¬â€ install the beacon-relay-agent runtime + first-boot
# provisioning into the rootfs. The agent itself is plain JS under
# beacon-relay-agent/ (built repo-side); this stage only stages the files and the
# systemd units that run them. The decrypt unit below carries the user's
# explicitly-requested inline comment about the auto-unlock keyfile tradeoff.
set -euo pipefail
TARGET=$1

# --- runtime placement ------------------------------------------------------
# Source tree is GENERATED by build.js from repo-root beacon-relay-agent/ (see the
# header there). cp -a (not -r) so exec bits/modes survive staging; . (not *)
# so dotfiles are included and an empty/glob-miss source errors instead of
# silently staging nothing.
mkdir -p "$TARGET/opt/beacon-relay-agent"
cp -a /work/pipeline/rootfs_files/opt/beacon-relay-agent/. "$TARGET/opt/beacon-relay-agent/"

# Presence gate — build-time, not boot-time. The rootfs MUST contain the full
# agent incl. the Step 1 security-signal modules; a tree that stages without
# them produced an appliance that monitors nothing while reporting healthy.
for f in agent.js provision.js \
         lib/graph.js lib/post_event.js lib/signal_emit.js lib/backup_risk.js \
         lib/enroll.js lib/issue_cert.js lib/tpm.js \
         lib/http_json.js lib/net_checks.js lib/fhir_r4.js lib/mirth_admin.js lib/ehr_check.js; do
  [ -f "$TARGET/opt/beacon-relay-agent/$f" ] || {
    echo "30-agent: MISSING $f in staged rootfs (agent source not generated by build.js?)" >&2
    exit 1
  }
done

# --- systemd: LUKS auto-unlock via TPM-sealed keyfile -------------------------
# REDESIGN (security review): the previous unit stored the LUKS unlock keyfile
# on the plaintext /boot partition (sda2) — the same physical disk as the
# LUKS-protected /data partition (sda5) it unlocks. An attacker who removes the
# drive reads /boot and unlocks /data: the stolen-drive threat model was
# defeated by construction. The keyfile is now SEALED INTO THE TPM at a
# persistent handle; the sealed blob lives on /data (ciphertext at rest) and is
# useless off this device. Reuses the same tpm2 seal mechanism as
# beacon-relay-agent/lib/tpm.js — one mechanism, not two.
cat > "$TARGET/etc/systemd/system/decrypt-data.service" <<'EOF'
[Unit]
Description=Unlock beacon-relay LUKS data partition using a TPM-sealed keyfile
DefaultDependencies=no
After=systemd-modules-load.service systemd-udev-settle.service
Before=local-fs-pre.target shutdown.target
Conflicts=shutdown.target

[Service]
Type=oneshot
# by-label links need udev settled; without it the first-boot race makes
# decrypt-data exit before /dev/disk/by-label/DATA exists (serial probe verified).
StandardOutput=journal+console
StandardError=journal+console
ExecStartPre=/usr/bin/udevadm settle --timeout=30
# ── THREAT-MODEL BOUNDARY ───────────────────────────────────────────────
# The LUKS unlock key is SEALED INTO THE TPM. The sealed BLOB (encrypted to
# this device's TPM, useless without it) lives on /boot — /boot is plaintext,
# but the blob is ciphertext to anyone without the TPM, so a stolen SSD yields
# nothing an attacker can unseal. The plaintext key is generated in /run
# (tmpfs), used once for luksFormat, then shredded — never written to disk.
# There is no passphrase fallback; do not add one without re-reading this
# boundary (a fallback re-opens the same physical attack this closes).
# Availability tradeoff (kept): no network unlock server, so a WAN outage can
# never block local boot; the cost is that a failed TPM = lost /data, which is
# the correct call for a field appliance whose /data holds only regenerable
# state (certs re-enroll, telemetry re-accumulates).
# ─────────────────────────────────────────────────────────────────────────
ExecStart=/bin/sh -c '\
  echo "decrypt: TPM-sealed unlock path"; \
  mkdir -p /data; \
  mkdir -p /boot; mount -o rw /dev/sda2 /boot || { echo "decrypt: MOUNT FAILED"; exit 1; }; \
  if [ ! -e /dev/mapper/beacon-relay-data ]; then \
    if [ ! -f /boot/luks.sealed.priv ]; then \
      echo "decrypt: first boot — generating + TPM-sealing LUKS key"; \
      # 128 bytes: a TPM2 sealed-data object's sensitive buffer (data + auth
      # overhead) overflows at 256 ("structure is the wrong size", verified in
      # the guest). 128 bytes is comfortably under the limit and ample entropy
      # for a LUKS keyfile.
      dd if=/dev/urandom of=/run/luks.key.plain bs=128 count=1 status=none; \
      chmod 0400 /run/luks.key.plain; \
      cryptsetup luksFormat --batch-mode /dev/sda5 /run/luks.key.plain || { echo "decrypt: LUKSFORMAT FAILED"; exit 1; }; \
      umask 077; mkdir -p /run/tpm; \
      tpm2_createprimary -C o -g sha256 -G rsa -c /run/tpm/luks.primary.ctx; \
      tpm2_create -g sha256 -u /boot/luks.sealed.pub -r /boot/luks.sealed.priv -C /run/tpm/luks.primary.ctx -i /run/luks.key.plain; \
      tpm2_flushcontext -t; \
      shred -u /run/luks.key.plain; \
      echo "decrypt: key sealed to TPM; encrypted blob on /boot (useless off-device)"; \
    fi; \
    echo "decrypt: loading sealed blob + unsealing via TPM"; \
    mkdir -p /run/tpm; \
    tpm2_createprimary -C o -g sha256 -G rsa -c /run/tpm/luks.primary.ctx; \
    tpm2_flushcontext -t; \
    tpm2_load -C /run/tpm/luks.primary.ctx -u /boot/luks.sealed.pub -r /boot/luks.sealed.priv -n /run/tpm/luks.name -c /run/tpm/luks.ctx; \
    tpm2_unseal -c /run/tpm/luks.ctx | cryptsetup open --key-file - /dev/sda5 beacon-relay-data || { echo "decrypt: TPM unseal/open FAILED"; exit 1; }; \
    rm -rf /run/tpm; \
    echo "decrypt: opened"; \
    if ! blkid /dev/mapper/beacon-relay-data >/dev/null 2>&1; then \
      echo "decrypt: no filesystem on data partition; mkfs.ext4"; \
      mkfs.ext4 -q /dev/mapper/beacon-relay-data || { echo "decrypt: MKFS FAILED"; exit 1; }; \
      udevadm settle --timeout=30; \
      echo "decrypt: filesystem created"; \
    fi; \
  else \
    echo "decrypt: already open"; \
  fi; \
  mount /dev/mapper/beacon-relay-data /data && echo "decrypt: /data mounted"; \
  echo "decrypt: mounting ESP at /boot/efi (RAUC grubenv access)"; \
  mkdir -p /boot/efi; \
  mount -o rw /dev/sda1 /boot/efi || echo "decrypt: ESP mount failed (OTA slot-switching unavailable; non-fatal)"'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
# Key file mode + LuksFormat(andFormat) above must match the agent's keyless
# path expectations exactly; do not soften to passphrase fallback.

# --- systemd: first-boot provisioning -------------------------------------
cat > "$TARGET/etc/systemd/system/beacon-relay-firstboot.service" <<'EOF'
[Unit]
Description=Beacon Relay first-boot provisioning (enroll into quarantine)
After=decrypt-data.service network-online.target
Requires=decrypt-data.service
Wants=network-online.target
ConditionPathExists=!/data/enrolled

[Service]
Type=oneshot
StandardOutput=journal+console
StandardError=journal+console
ExecStart=/usr/local/bin/node /opt/beacon-relay-agent/provision.js
# Enrollment is one-shot; the renewal loop runs as the agent's daemon unit.

[Install]
WantedBy=multi-user.target
EOF

# --- systemd: ongoing agent (renewal loop + heartbeats) --------------------
cat > "$TARGET/etc/systemd/system/beacon-relay-agent.service" <<'EOF'
[Unit]
Description=Beacon Relay device agent (renewal loop + monitoring orchestrator)
After=beacon-relay-firstboot.service
ConditionPathExists=/data/enrolled

[Service]
Type=simple
ExecStart=/usr/local/bin/node /opt/beacon-relay-agent/agent.js
Restart=always
# journal+console: the acceptance harness and any field debugging read the
# agent's heartbeat/renewal lines off the serial console; without this the
# daemon's output is invisible outside the journal (both sibling units match).
StandardOutput=journal+console
StandardError=journal+console
# Renewal cadence ~50-55% of TTL lives in the agent, not here Ã¢â‚¬â€ a sysadmin
# editing the unit must not be able to widen the expiry silence window.

[Install]
WantedBy=multi-user.target
EOF

# --- RAUC daemon unit --------------------------------------------------------
# Debian bookworm's `rauc` package ships ONLY /usr/bin/rauc (verified with
# dpkg-deb): no D-Bus service file, no systemd unit. Without a daemon,
# `rauc status` / `rauc install` / `rauc status mark-good` all fail with a
# D-Bus service-not-found error — which is exactly why markGood() failed
# (non-fatally) on every boot. This unit runs the daemon; ordering waits for
# decrypt-data.service so the ESP (grubenv) is already mounted when RAUC
# starts.
cat > "$TARGET/etc/systemd/system/rauc.service" <<'EOF'
[Unit]
Description=RAUC update daemon (install/status/mark-good over D-Bus)
After=decrypt-data.service

[Service]
StandardOutput=journal+console
StandardError=journal+console
ExecStart=/usr/bin/rauc service
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
# D-Bus name-ownership policy for the RAUC daemon. This file is verbatim
# upstream RAUC (data/de.pengutronix.rauc.conf): Debian's package omits it,
# and this image's dbus system.conf has <deny own="*"/> with no root own-
# allow, so without it the daemon dies in a restart loop with "Failed to
# obtain name de.pengutronix.rauc on system bus" (verified on-device).
mkdir -p "$TARGET/usr/share/dbus-1/system.d"
cat > "$TARGET/usr/share/dbus-1/system.d/de.pengutronix.rauc.conf" <<'EOF'
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <!-- This config allows anyone to control rauc -->
  <!-- It is usually installed to /usr/share/dbus-1/system.d -->

  <policy context="default">
    <allow send_destination="de.pengutronix.rauc"/>
  </policy>

  <policy user="root">
    <allow own="de.pengutronix.rauc"/>
  </policy>
</busconfig>
EOF
# --- binaries the rootfs needs but debootstrap leaves out -----------------
# rauc is the OTA update client (spec §3: poll CP for signed bundle, verify
# before touching disk, apply to inactive slot, mark good after boot). It was
# missing entirely before — an appliance that can't update itself is a brick
# the first time a CVE drops.
chroot "$TARGET" apt-get update
chroot "$TARGET" apt-get install -y --no-install-recommends \
  systemd-sysv nodejs cryptsetup ca-certificates \
  linux-image-amd64 grub-efi-amd64-bin grub-common tpm2-tools openssl rauc
# Triggered once: previous builds installed _some_ bundles but never
# /usr/sbin/init, and an unsquashfs probe showed the missing binary. Make
# this an explicit gate so sub-package resolution can't silently slip in.
if ! chroot "$TARGET" test -f /usr/sbin/init; then
  echo "systemd-sysv install did not produce /usr/sbin/init" >&2
  exit 1
fi
# grub-editenv (grub-common) is how RAUC's grub backend writes boot state
# on-device — without it an update installs but the slot can never be marked
# good, so rollback accounting silently never happens. Gate like init above.
if ! chroot "$TARGET" test -f /usr/bin/grub-editenv; then
  echo "grub-common install did not produce /usr/bin/grub-editenv" >&2
  exit 1
fi
# The agent's update client compares this against the CP's latest-release
# pointer (lib/update.js); it must be the release being built, not a default.
echo "${RELEASE_VERSION:-0.1.0}" > "$TARGET/etc/beacon-relay-version"
cat > "$TARGET/usr/local/bin/node" <<'EOF'
#!/bin/sh
exec /usr/bin/node "$@"
EOF
chmod +x "$TARGET/usr/local/bin/node"

# systemd-networkd must be explicitly enabled — the wired DHCP config in
# 10-configure.sh is inert without it, and an appliance that boots with no IP
# can never enroll (provision.js saw ENETUNREACH/0.0.0.0 before this was on).
# rauc.service is enabled alongside: the agent's update/mark-good path calls
# into it via D-Bus (see the unit comment above).
systemd-nspawn --directory="$TARGET" --quiet /bin/systemctl enable \
  systemd-networkd decrypt-data.service beacon-relay-firstboot.service beacon-relay-agent.service rauc.service \
  2>/dev/null || \
chroot "$TARGET" /bin/sh -c \
  'systemctl enable systemd-networkd decrypt-data.service beacon-relay-firstboot.service beacon-relay-agent.service rauc.service'

