#!/usr/bin/env bash
# pipeline/assemble_image.sh — turn /out/<version> artifacts into a single
# flashable disk image (netbox-disk.img) using the declarative partition map.
# Requires a privileged container (loop devices, mount). Layout breaks MUST
# stay in pipeline/manifests/netbox-partition-map.json, not here.
set -euo pipefail
VERSION=${1:?version}
SIZE_MB=${2:-5120}
IMG=/out/$VERSION/netbox-disk.img
MAP=/work/pipeline/manifests/netbox-partition-map.json

# Loop exhaustion dead letters: dead `docker compose ... run` containers hold
# loops even after exit, so a naive losetup -f resurrects failures forever.
# Find free explicitly, creating /dev/loop* nodes as needed.
: > "$IMG"; truncate -s "${SIZE_MB}M" "$IMG"
LOOP=""
losetup -D >/dev/null 2>&1 || true
for n in $(seq 0 255); do
  DEV=/dev/loop$n
  if ! [ -b "$DEV" ]; then
    if ! mknod -b 7 "$n" "$DEV" 2>/dev/null; then
      continue
    fi
  fi
  if losetup "$DEV" "$IMG" 2>/dev/null; then LOOP=$DEV; break; fi
done
[ -z "$LOOP" ] && { echo "no free loop device" >&2; exit 1; }
parted -s "$IMG" mklabel gpt

# Walk the map left-to-right; parted needs MiB math, which only accepts
# MiB|GiB suffixes here so the map can't drift into random units.
CUR=1
N=$(jq '.partitions | length' "$MAP")
for i in $(seq 0 $((N-1))); do
  label=$(jq -r ".partitions[$i].label" "$MAP")
  size=$(jq -r ".partitions[$i].size" "$MAP")
  type=$(jq -r ".partitions[$i].type" "$MAP")
  if [ "$size" = "grow" ]; then
    end="100%"
  else
    case "$size" in
      *MiB) mib=${size%MiB} ;;
      *GiB) mib=$(( ${size%GiB} * 1024 )) ;;
      *) echo "unsupported unit: $size" >&2; exit 1 ;;
    esac
    end="$(( CUR + mib ))MiB"
  fi
  case "$type" in fat32) fst="fat32";; *) fst="$type";; esac
  parted -s "$IMG" mkpart "$label" "$fst" "${CUR}MiB" "$end"
  if [ "$type" = "fat32" ]; then parted -s "$IMG" set $((i+1)) esp on; fi
  [ "$size" != "grow" ] && CUR=$(( CUR + mib+1 ))
done

LOOP=$(losetup -f --show "$IMG")
kpartx -av "$LOOP" >/dev/null
BASE=/dev/mapper/$(basename "$LOOP")
trap 'kpartx -dv "$LOOP" >/dev/null 2>&1 || true; losetup -d "$LOOP"' EXIT

for i in $(seq 0 $((N-1))); do
  IDX=$((i+1))
  LABEL=$(jq -r ".partitions[$i].label" "$MAP")
  TYPE=$(jq -r ".partitions[$i].type" "$MAP")
  ROLE=$(jq -r ".partitions[$i].role" "$MAP")
  dev="${BASE}p$IDX"
  case "$TYPE" in
    fat32) mkfs.vfat -n "$LABEL" "$dev" ;;
    ext2)  mke2fs -q -t ext2 -L "$LABEL" -F "$dev" ;;
    # grub's ext2 driver rejects ext4 metadata_csum -> every kernel path
    # failed before this. Disable checksum on RAID slots (+DATA too: same
    # journey if spec ever mounts from grub).
    ext4)  [ "$ROLE" != "luks-data" ] && OPT="-O ^metadata_csum" || OPT=
           mkfs.ext4 -q $OPT -L "$LABEL" -F "$dev" ;;
  esac
  if [ "$ROLE" = "rauc-slot-rootfs.0" ]; then
    TMP=$(mktemp -d)
    mount "$dev" "$TMP"
    # Extract directly into the slot root. Earlier -d "$TMP/root" nested the
    # rootfs one level deep, and initramfs reported /sbin/init missing (found
    # at p3/root/sbin instead), which then cascaded to PXE fallback silently.
    unsquashfs -f -d "$TMP" "/out/$VERSION/payload/rootfs.ext4" >/dev/null

    # Bootloader install ONTO THE ESP (non-RAUC partition). Kernel/initramfs
    # inside the rootfs slot; EFI shell entry 'BOOTX64' executes grubx64.efi,
    # grub.cfg references slots by label so RAUC slot flips don't re-touch EFI.
    ESP=$(mktemp -d)
    mount "/dev/mapper/$(basename "$LOOP")p1" "$ESP"
    # Embedded ESP payload is generated by grub-mkimage (worker-side, not the
    # rootfs): grubx64.efi carries the /grub prefix and the modules needed to
    # resolve ROOTFS labels; choosing package-installed binaries would freeze
    # the modules set, which was the source of the earlier missing-binary bug.
    mkdir -p "$ESP/EFI/BOOT" "$ESP/grub"
    # Imaged cfg path is unreliable on ESP; embed the config into the binary
    # itself via `grub-mkimage -c`. Boot stops happening via prompt fallback.
    # Imaged cfg: fixed GPT walk is deterministic; label-search on OVMF/AHCI
    # was failing to resolve before normal-module prompt landed (verified).
    # Symlink traversal in the ext2 driver was masking kernel resolution;
    # explicit paths + an 'ls' line give grounded evidence, not syntax errors.
    # Embedded cfg with no 'normal' fallback drops into prompt on complete.
    # Instead install a proper ESP /grub/grub.cfg and fix the prefix to it.
    # Kill the ext4-in-grub path outright: kernel+initrd copied onto ESP too,
    # and the cfg reads FROM ESP — no ext driver chain in the bootlin path.
    cp "$TMP/boot/vmlinuz-6.1.0-50-amd64" "$ESP/"
    cp "$TMP/boot/initrd.img-6.1.0-50-amd64" "$ESP/"
    cat > "$ESP/grub/grub.cfg" <<'EOF'
set default=0
set timeout=2
set root=(hd0,gpt1)
linux /vmlinuz-6.1.0-50-amd64 root=LABEL=ROOTFS_A ro console=ttyS0 init=/lib/systemd/systemd
initrd /initrd.img-6.1.0-50-amd64
boot
EOF
    cat > /tmp/grub.embed.cfg <<'EOF'
echo NETBOX_EMBED_START
ls (hd0,gpt1)/grub/
echo NETBOX_EMBED_END
configfile (hd0,gpt1)/grub/grub.cfg
EOF
    grub-mkimage -O x86_64-efi -c /tmp/grub.embed.cfg -p "(hd0,gpt1)/grub" -o /tmp/grubx64.efi \
      part_gpt fat ext2 linux normal configfile search search_label
    cp /tmp/grubx64.efi "$ESP/EFI/BOOT/BOOTX64.EFI"
    cmp /tmp/grubx64.efi "$ESP/EFI/BOOT/BOOTX64.EFI"
    ls -lR "$ESP"
    umount "$ESP"; rmdir "$ESP"
    umount "$TMP"; rmdir "$TMP"
  fi
done
kpartx -dv "$LOOP" >/dev/null 2>&1 || true
losetup -d "$LOOP"; trap - EXIT
echo "disk image: $IMG"
